name: OpenVSCode Server mixin
files:
  - src: dist/openvscode-server-v1.109.5-linux-x64.tar.gz
    dest: /root/openvscode-server.tar.gz
    mode: "0644"
  - src: openvscode-server.service
    dest: /etc/systemd/system/openvscode-server.service
    mode: "0644"
# online alternative (requires curl):
#post_create_commands:
#  - curl -fsSL https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.109.5/openvscode-server-v1.109.5-linux-x64.tar.gz -o /tmp/openvscode-server.tar.gz
post_create_commands:
  - tar -xzf /root/openvscode-server.tar.gz -C /opt/
  - mv /opt/openvscode-server-v1.109.5-linux-x64 /opt/openvscode-server
  #- rm /tmp/openvscode-server.tar.gz
  - systemctl daemon-reload
  - systemctl enable openvscode-server
  - systemctl start openvscode-server
