DROP TABLE IF EXISTS instances;
DROP TABLE IF EXISTS volumes;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS servers;
DROP TABLE IF EXISTS secrets;
DROP TABLE IF EXISTS ssh_keys;
DROP TABLE IF EXISTS users;
